# This is a basic workflow to help you get started with Actions

name: Api Test

env:
  accesskey:  ${{ secrets.ACCESSTOKEN }}
  APIUrl: ${{ secrets.APIURL }}
  
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Run Tests Across Node.js Versions and Operating Systems
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v1
      - name: Run API Tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome:headless ./WeatherAPITest/tests  --skip-js-errors --disable-page-caching"


  

    
