name: Otrium E2E Test

env:
  email: ${{ secrets.EMAIL }} 
  password: ${{ secrets.PASSWORD }} 
  otrium_url: ${{ secrets.OTRIUM_URL }}
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Run Tests Across Node.js Versions and Operating Systems
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v1
      - name: Run Otrium E2E Tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome:headless  ./Otrium_Automation/tests  --skip-js-errors --disable-page-caching "
